services:
  web_server:
    # Usa a imagem oficial do NGINX
    image: nginx:latest
    container_name: frontend_nginx
    
    # Mapeia as portas: Porta_Externa:Porta_Interna
    # Aqui, a porta 80 da sua máquina será mapeada para a porta 80 do contêiner (padrão do NGINX)
    ports:
      - "80:80"
    
    # Mapeia o volume: Pasta_Local:Pasta_No_Container
    # Mapeia a pasta 'frontend' para o diretório de conteúdo do NGINX
    # Mapeia templates e config gerado com envsubst
    volumes:
      - /home/ubuntu/frontend:/usr/share/nginx/html
      - /home/ubuntu/frontend/nginx/templates:/etc/nginx/templates
      - /home/ubuntu/frontend/nginx/conf.d:/etc/nginx/conf.d
    
    # Reinicia o contêiner automaticamente, a menos que ele seja parado explicitamente.
    restart: unless-stopped